apiVersion: v1
kind: Service
metadata:
  name: eve-bot-v1
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: api
    - port: 3001
      targetPort: 3001
      name: metrics
  selector:
    app: eve-bot-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-bot-v1
  namespace: default
spec:
  selector:
    matchLabels:
      app: eve-bot-v1
  replicas: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-env: "kv/data/devops/eve"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "kv/data/devops/eve" -}}
          {{ range $k, $v := .Data.data }}
          export {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}
        vault.hashicorp.com/role: "k8s-devops"
      labels:
        app: eve-bot-v1
    spec:
      securityContext:
        runAsUser: 9001
        runAsGroup: 9001
        fsGroup: 65534
      containers:
        - name: eve-bot-v1
          image: unanet-docker.jfrog.io/eve-bot:0.1.0
          imagePullPolicy: Always
          env:
            - name: EVE_LOG_LEVEL
              value: "debug"
            - name: EVEBOT_EVEAPI_BASE_URL
              value: "https://eve-api.unanet.io"
            - name: EVEBOT_EVEAPI_CALLBACK_URL
              value: "https://eve-bot.unanet.io/eve-callback"
            - name: EVE_SERVICE_NAME
              value: "eve-bot"
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 3001
              name: metrics
      imagePullSecrets:
        - name: docker-cfg
