stages:
  - details
  - build
  - publish
  - tag
  - changelog

details:
  stage: details
  script:
    - make details
  tags:
    - linux
  except:
    - tags    

build:
  stage: build
  script:
    - make build
  tags:
    - linux
  except:
    - tags    

publish:
  stage: publish
  script:
    - make publish
  tags:
    - linux
  only:
    - master
    - patch

tag:
  stage: tag
  script:
    - make tag
  tags:
    - linux
  only:
    - master
    - patch

changelog:
  stage: changelog
  script:
    - make changelog
  tags:
    - linux
  only:
    - master
    - patch  
  