stages:
  - build
  - publish
  - tag
  - release

build:
  stage: build
  script:
    - make
  tags:
    - linux
  except:
    - tags    

publish:
  stage: publish
  script:
    - make publish
  tags:
    - linux
  only:
    - master
    - patch

tag:
  stage: tag
  script:
    - make tag
  tags:
    - linux
  only:
    - master
    - patch

release:
  stage: release
  script:
    - make release
  tags:
    - linux
  only:
    - tags
  