stages:
  - details
  # - build

details:
  stage: details
  script:
    - make show-version
    - make git-details
    - make build-details
  tags:
    - linux
  only:
    - master  

# build:
#   stage: build
#   script:
#     - make
#   tags:
#     - linux
#   only:
#     - master
