default:
  image: 'golang:latest'
  before_script:
    - echo Hello World

stages:
  - build

build-image:
  stage: build
  inherit:
    default: [image]  
  script:
    - make push
  tags:
    - linux
  only:
    - master
