stages:
  - build
  - deploy

Dist:
  stage: build
  script:
    - make dist
  tags:
    - linux
  only:
    - master

Deploy:
  stage: deploy
  script:
    - make deploy
  tags:
    - linux
  only:
    - master

Build:
  stage: build
  script:
    - make build
  tags:
    - linux
  except:
    - master
    - tags
