stages:
  - build

Dist:
  stage: build
  script:
    - make dist
  tags:
    - linux
  only:
    - master

Build:
  stage: build
  script:
    - make build
  tags:
    - linux
  except:
    - master
    - tags
