stages:
  - details
  - build
  - publish

details:
  stage: details
  script:
    - make details
  tags:
    - linux

build:
  stage: build
  script:
    - make build
  tags:
    - linux

publish:
  stage: publish
  script:
    - make publish
  tags:
    - linux
  only:
    - master
