---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-bot-v1
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: eve-bot-v1
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
      labels:
        app: eve-bot-v1
        metrics: enabled
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      securityContext:
        runAsUser: 9001
        runAsGroup: 9001
        fsGroup: 65534
      containers:
        - name: eve-bot-v1
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: {{ .Values.eveLogLevel }}
            - name: SERVICE_NAME
              value: {{ .Values.eveServiceName }}
            - name: EVEBOT_EVEAPI_BASE_URL
              value: {{ .Values.eveAPIBaseURL }}
            - name: EVEBOT_EVEAPI_CALLBACK_URL
              value: {{ .Values.eveAPICallbackURL }}
            - name: EVEBOT_SLACK_OAUTH_ACCESS_TOKEN
              value: {{ .Values.eveSlackOAuthAccessToken }}
            - name: EVEBOT_SLACK_SIGNING_SECRET
              value: {{ .Values.eveSlackSigningSecret }}
            - name: EVEBOT_SLACK_VERIFICATION_TOKEN
              value: {{ .Values.eveSlackVerificationToken }}
            - name: VAULT_ROLE
              value: {{ .Values.vaultRole }}
            - name: VAULT_ADDR
              value: {{ .Values.vaultAddr }}
            - name: VAULT_K8S_MOUNT
              value: {{ .Values.vaultK8sMount }}
            - name: EVEBOT_SLACK_CHANNELS_AUTH
              value: "eve-admin"
            - name: EVEBOT_SLACK_AUTH_ENABLED
              value: "true"
            - name: EVEBOT_SLACK_CHANNELS_MAINTENANCE
              value: "eve-maintenance"
            - name: EVEBOT_SLACK_MAINTENANCE_ENABLED
              value: "false"
            - name: EVEBOT_EVEAPI_ADMIN_TOKEN
              value: {{ .Values.adminToken }}
            - name: EVEBOT_PORT
              value: "3000"
            - name: PROVIDER_TYPE
              value: {{ .Values.secretsProviderType }}
            - name: DYNAMIC_SECRETS_ENABLED
              value: {{ .Values.dynamicSecretsEnabled | quote }}
            - name: EVEBOT_USER_TABLE_NAME
              value: {{ .Values.eveUserTableName }}
            - name: EVEBOT_IDENTITY_CONN_URL
              value: {{ .Values.eveIdentityConnURL }}
            - name: EVEBOT_IDENTITY_REDIRECT_URL
              value: {{ .Values.eveIdentityRedirectURL }}
            - name: EVEBOT_IDENTITY_CLIENT_ID
              value: {{ .Values.eveIdentityClientID }}
            - name: EVEBOT_IDENTITY_CLIENT_SECRET
              value: {{ .Values.eveIdentityClientSecret }}
            - name: EVEBOT_AWS_REGION
              value: {{ .Values.eveAWSRegion }}
            - name: AWS_REGION
              value: {{ .Values.awsRegion }}            
            - name: AWS_ACCESS_KEY
              value: {{ .Values.awsAccessKey }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.awsSecretKey }}
            - name: EVEBOT_LOGGING_DASHBOARD_BASE_URL
              value: {{ .Values.eveLoggingDashboard }}
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 3001
              name: metrics
      imagePullSecrets:
        - name: docker-cfg
